[project]
name = "production-grade-rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.15.0",
    "langchain>=1.4.3",
    "langchain-ollama>=1.1.0",
    "langchain-openai>=1.7.0",
    "pypdf>=6.19.0",
    "pytest>=9.1.1",
    "python-dotenv>=1.2.4",
    "ragas>=0.4.3",
    "sentence-transformers>=6.1.0",
    "weaviate-client>=4.23.1",
]

[project.scripts]
production-grade-rag = "production_grade_rag:main"

[build-system]
requires = ["uv_build>=0.12.23,<0.13.0"]
build-backend = "uv_build"
